### ISSUE TITLE
issue in this code u may know the solution

### ISSUE THREAD

**Issue by mohannadalaa** [yusufuzun/of-dbscan-object-detection#1]
hi yusuf i am mohannad 
i am implementing an optical flow tracker algorithm i already finished it but it tracks all motion in every frame .. my project is to track a single object (player and ball) in my project i get the initial position by user of the tracked object then i should track this area .. i still cant do this ... i watched this code which i am interested in in my project but i got some issues i cant get it on .. i put the 3.1 dlls all in its place but it gives me 3 error i can't handle could you help me with them or provide me with your email ..
the first error 
Metadata file 'C:\Users\Mohannad\Downloads\of-dbscan-object-detection-master\Detect\bin\Debug\Detect.dll' could not be found
the second one 
The type or namespace name 'Capture' could not be found (are you missing a using directive or an assembly reference?)
and a message

The designer cannot process unknown name 'imageBox1' at line 34.  The code within the method 'InitializeComponent' is generated by the designer and should not be manually modified.  Please remove any changes and try opening the designer again.

could you cantact me or help me with that .. and dont worry i just will understand how it will work to help me in my project
my email : mohanadalaa1994@hotmail.com

![asas](https://cloud.githubusercontent.com/assets/24613376/24870479/b482ec78-1e16-11e7-82bc-1e0f3ba0f1f6.PNG)

**Comment by yusufuzun** [comment]
Hi mohannad,
You have to put EmguCV files into x86 folder, not root. Then after change their properties "Copy to output directory" to "copy if newer". Then it must work correctly. I put screenshot below: 

![image](https://cloud.githubusercontent.com/assets/5049395/25070687/227f06e4-22ae-11e7-8086-2275ec975f13.png)

**Comment by mohannadalaa** [comment]
Hi yusuf
Thanks for your reply :)
i made a new project then i put the files on it and it works ..  its hard working from you (Y) .. i am working on the same algorithm now but my aim to track only 1 person (player) of the other players .. i have a deadline in about 2 weeks and i am stuck on it do you have any advice to how to do it .. i am choosing first the player coordinates by user input then i should tack the rectangle surrounding this coordinates.
thank again .

Sent from Windows Mail
